"""由 :class:`PackageSpec` 渲染 Allegro SKILL 脚本与运行装置。

源程序的 ``build_wson8.il`` / ``verify.il`` / ``props.il`` 是把器件数值
直接写死在脚本里的（L5-L9、L166-L203、L250-L274）。这里改成
「模板 + 参数」：同一个模板族可以生成 WSON / DFN / QFN 的脚本，
而且每次生成都是可快照、可回归的纯文本。

三条从源程序保留的**硬约定**：

1. **cwd 决定加载哪个 .il** —— Allegro 只自动读启动目录下的
   ``allegro.ilinit``，所以要切换任务必须同时换 ilinit 的 load 目标与 .scr，
   两者不同步就白跑（源程序靠手工替换，这里由 :func:`write_skill_package` 一并写齐）。
2. **矩形体必须用 4 条 NewLine 拼** —— ``NewBox`` 在该环境恒返回
   ``statusFailed=1``（与 Cadence 自家 ``PwlANDSymbolCreate.tcl`` 同法）。
3. **无头模式必须 ``?noConfirm t``** —— 否则卡在保存确认框上（GUI 会话日志
   ``allegro.jrl`` 里留下了 ``Do you want to save the changes…?`` 的反面证据）。

SKILL 没有一元负号，负数一律写成 ``0.0 - X``（源程序 L175-L178、L197-L203、
L258-L261 全用这个形式）。
"""

from __future__ import annotations

from pathlib import Path

from backend.agents.pcb.derive import DerivedPackage, PinPlacement
from backend.agents.pcb.spec import PackageSpec

#: Allegro 可接受的层名白名单（``_scratch/probe_layers2.log` 实测）。
#: 非法层名不会报错，只静默返回 nil，几何直接丢失 —— 所以生成前要校验。
ALLOWED_LAYERS: frozenset[str] = frozenset(
    {
        "PACKAGE GEOMETRY/ASSEMBLY_TOP",
        "PACKAGE GEOMETRY/PLACE_BOUND_TOP",
        "PACKAGE GEOMETRY/SILKSCREEN_TOP",
        "REF DES/ASSEMBLY_TOP",
        "REF DES/SILKSCREEN_TOP",
    }
)

#: padstack 内部的层名是另一套命名空间（不带 class 前缀）。
PADSTACK_LAYERS: tuple[str, str, str] = ("TOP", "PASTEMASK_TOP", "SOLDERMASK_TOP")


def paren_depth(text: str) -> int:
    """SKILL 源码的括号净深度（跳过字符串字面量与转义）。

    非 0 表示生成器写坏了 —— 这类错误在 Allegro 侧只会表现为
    ``errset`` 吞掉的一个 ``nil``，排查成本极高，所以在生成阶段就拦住。
    """
    depth = 0
    in_string = False
    escaped = False
    for char in text:
        if escaped:
            escaped = False
            continue
        if char == "\\":
            escaped = True
            continue
        if char == '"':
            in_string = not in_string
            continue
        if in_string:
            continue
        if char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
    return depth


def check_layers() -> list[str]:
    """返回本模块会用到、但不在白名单里的层名（应为空）。"""
    used = {
        "PACKAGE GEOMETRY/ASSEMBLY_TOP",
        "PACKAGE GEOMETRY/PLACE_BOUND_TOP",
        "PACKAGE GEOMETRY/SILKSCREEN_TOP",
        "REF DES/ASSEMBLY_TOP",
        "REF DES/SILKSCREEN_TOP",
    }
    return sorted(used - ALLOWED_LAYERS)


def _num(value: float) -> str:
    """SKILL 数字字面量（两位小数，与源程序写法一致）。"""
    return f"{value:.2f}"


def _signed(value: float) -> str:
    """SKILL 没有一元负号，负数写成 ``0.0 - X``。"""
    return f"0.0 - {_num(abs(value))}" if value < 0 else _num(value)


def _posix(path: Path) -> str:
    """SKILL 字符串里的路径用正斜杠。"""
    return str(path).replace("\\", "/")


def _pin_call(pin: PinPlacement, *, has_ep: bool) -> str:
    """一行 ``bAddPin(...)``。

    负数参数**加括号**：``0.0 - 1.15 0.0 - 0.25`` 这样两个 ``0.0 - X`` 连排时，
    虽然 SKILL 的中缀解析能正确断句，但读的人（以及未来的解析器）会犯迷糊，
    源程序用 ``m115``/``m25`` 这类变量正是为了回避这一点。
    """

    def arg(value: float) -> str:
        return f"({_signed(value)})" if value < 0 else _num(value)

    tx, ty = pin.text_offset
    return (
        f'    bAddPin("{pin.number}" {arg(pin.x)} {arg(pin.y)} '
        f"{arg(tx)} {arg(ty)})"
    )


def _log_procedure(name: str, log_var: str, sentinel: str) -> str:
    """三份脚本共用的「开-写-关」日志过程。

    每次调用都重新 open/drain/close —— 慢，但 SKILL 中途硬崩时已写的证据
    仍在盘上（源程序 verify.il 的注释把它总结为「安全读取在前、危险属性在后」）。
    """
    return f"""procedure({name}(msg)
  prog((port)
    port = outfile({log_var} "a")
    if(port then
      fprintf(port "%s\\n" msg)
      drain(port)
      close(port)
    else
      printf("{sentinel}\\n")
    )
    t
  )
)"""


def _preamble(spec: PackageSpec, work_dir: Path, log_name: str) -> str:
    """文件头 + 路径常量（对应源程序 L1-L9）。"""
    source = f"\\n; Geometry source: {spec.drawing_code}" if spec.drawing_code else ""
    return f"""; {spec.family} {spec.body_x}x{spec.body_y} land pattern builder for Cadence Allegro (AXL-SKILL).{source}
; Generated by backend/agents/pcb/skill_emitter.py — do not hand-edit.
; Run headless: allegro -sq -product <prod> -s <script>.scr <template>.dra

bWork  = "{_posix(work_dir)}"
bLogF  = strcat(bWork "/{log_name}")
bName  = "{spec.name}"
bLand  = "{spec.land_padstack_name}"{f'''
bEp    = "{spec.ep_padstack_name}"''' if spec.ep_present else ""}"""


# ── build.il ─────────────────────────────────────────────────────


def emit_build_skill(
    spec: PackageSpec, derived: DerivedPackage, work_dir: Path
) -> str:
    """渲染 ``build_<name>.il``：建焊盘 → 摆引脚 → 画各层 → 存盘编译。"""
    land_pad = derived.land_pad
    lines: list[str] = []

    # ── bClearDesign（对应源程序 L25-L44）────────────────────────
    lines.append(
        """procedure(bClearDesign()
  prog((sel objs count pass)
    axlSetFindFilter(
      ?enabled list("noall" "alltypes")
      ?onButtons list("noall" "alltypes"))
    pass = 0
    while(pass < 6
      pass = pass + 1
      errset(axlAddSelectAll())
      sel = errset(axlGetSelSet())
      objs = if(sel then car(sel) else nil)
      count = if(objs then length(objs) else 0)
      bLog(sprintf(nil "CLEAR pass=%L found=%L" pass count))
      when(count > 0
        errset(axlDeleteObject(objs))
      )
    )
    t
  )
)

procedure(bRectPad(layer, xSize, ySize)
  make_axlPadStackPad(
    ?layer layer
    ?type 'REGULAR
    ?figure 'RECTANGLE
    ?figureSize (xSize:ySize)
    ?offset (0:0)
  )
)"""
    )

    # ── bMakePadstack（对应 L56-L73）─────────────────────────────
    lines.append(
        """procedure(bMakePadstack(name, landX, landY, pasteX, pasteY, maskX, maskY)
  prog((pads made disk reloaded)
    pads = list(
      bRectPad("TOP" landX landY)
      bRectPad("PASTEMASK_TOP" pasteX pasteY)
      bRectPad("SOLDERMASK_TOP" maskX maskY)
    )
    made = errset(axlDBCreatePadStack(name nil pads t))
    bLog(sprintf(nil "PADSTACK %s create=%L" name made))
    when(made && car(made)
      disk = errset(axlPadstackToDisk(name name))
      bLog(sprintf(nil "PADSTACK %s toDisk=%L" name disk))
      reloaded = errset(axlLoadPadstack(name))
      bLog(sprintf(nil "PADSTACK %s reload=%L" name reloaded))
    )
    made && car(made)
  )
)"""
    )

    # ── bAddPin / bAddEpPin（对应 L75-L94）───────────────────────
    pin_procs = """procedure(bAddPin(name, x, y, textOffsetX, textOffsetY)
  prog((txt res)
    txt = make_axlPinText(
      ?number name
      ?offset (textOffsetX:textOffsetY)
      ?text """
    pin_procs += f'"{spec.pin_text_block}")'
    pin_procs += """
    res = errset(axlDBCreatePin(bLand (x:y) txt 0.0))
    bLog(sprintf(nil "PIN %s xy=%L:%L result=%L" name x y res))
    res
  )
)"""
    if spec.ep_present:
        pin_procs += f"""

procedure(bAddEpPin(x, y)
  prog((txt res)
    txt = make_axlPinText(?number "{spec.ep_pin_number}" ?offset (0.0:0.0) ?text "{spec.pin_text_block}")
    res = errset(axlDBCreatePin(bEp (x:y) txt 0.0))
    bLog(sprintf(nil "PIN {spec.ep_pin_number} xy=%L:%L result=%L" x y res))
    res
  )
)"""
    lines.append(pin_procs)

    # ── bDumpDesign（对应 L96-L129）：判据的唯一数据源 ───────────
    lines.append(
        """procedure(bDumpDesign()
  prog((d drcs pins sel objs)
    d = errset(axlDBGetDesign())
    when(d && car(d)
      pins = errset(car(d)->pins)
      bLog(sprintf(nil "DUMP pin_count=%L"
        if(pins && car(pins) then length(car(pins)) else 0)))
      when(pins && car(pins)
        foreach(p car(pins)
          bLog(sprintf(nil "  PIN number=%L location=%L rot=%L pad=%L"
            errset(p->number)
            errset(p->location)
            errset(p->rotation)
            errset(p->padstack)))
        )
      )
    )
    axlSetFindFilter(
      ?enabled list("noall" "alltypes")
      ?onButtons list("noall" "alltypes"))
    errset(axlAddSelectAll())
    sel = errset(axlGetSelSet())
    objs = if(sel then car(sel) else nil)
    bLog(sprintf(nil "DUMP object_count=%L"
      if(objs then length(objs) else 0)))
    when(objs
      foreach(o objs
        bLog(sprintf(nil "  OBJ type=%L layer=%L bbox=%L"
          errset(o->objType) errset(o->layer) errset(o->bBox)))
      )
    )
    t
  )
)"""
    )

    # ── bMain ────────────────────────────────────────────────────
    ep_x = spec.ep_x or 0.0
    ep_y = spec.ep_y or 0.0
    ex0, ey0, ex1, ey1 = spec.extents

    body: list[str] = []
    body.append('    bLog("==== BUILD START ====")')
    body.append('    bLog(sprintf(nil "version=%L" axlVersion(\'fullVersion)))')
    body.append('    bLog(sprintf(nil "designType=%L" errset(axlDesignType())))')
    body.append("")
    body.append(
        f'    r = errset(axlDBChangeDesignUnits("{spec.units}" {spec.accuracy}))'
    )
    body.append('    bLog(sprintf(nil "setUnits mm/4 -> %L" r))')
    body.append('    pd = axlGetParam("paramDesign")')
    body.append("    units = errset(pd->units)")
    body.append("    accuracy = errset(pd->accuracy)")
    body.append('    bLog(sprintf(nil "units=%L accuracy=%L" units accuracy))')
    body.append("")
    body.append(
        "    r = errset(axlDBChangeDesignExtents(list("
        f"{_signed(ex0)}:{_signed(ey0)} {_num(ex1)}:{_num(ey1)})))"
    )
    body.append('    bLog(sprintf(nil "extents -> %L" r))')
    body.append("")
    body.append("    r = errset(axlRenameDesign(bName))")
    body.append('    bLog(sprintf(nil "rename %s -> %L" bName r))')
    body.append("")
    body.append('    r = errset(axlSetVariable("padpath" list(bWork)))')
    body.append('    bLog(sprintf(nil "padpath -> %L" r))')
    body.append('    r = errset(axlSetVariable("psmpath" list(bWork)))')
    body.append('    bLog(sprintf(nil "psmpath -> %L" r))')
    body.append("")
    body.append("    bClearDesign()")
    body.append("")
    body.append(f"    landX = {_num(spec.land_x)}")
    body.append(f"    landY = {_num(spec.land_y)}")
    body.append(
        f'    r = bMakePadstack(bLand landX landY landX landY '
        f"{_num(land_pad.mask[0])} {_num(land_pad.mask[1])})"
    )
    body.append('    bLog(sprintf(nil "land padstack ok=%L" r))')
    if spec.ep_present:
        body.append(f"    epX   = {_num(ep_x)}")
        body.append(f"    epY   = {_num(ep_y)}")
        assert derived.ep_pad is not None
        body.append(
            f'    r = bMakePadstack(bEp epX epY epX epY '
            f"{_num(derived.ep_pad.mask[0])} {_num(derived.ep_pad.mask[1])})"
        )
        body.append('    bLog(sprintf(nil "ep padstack ok=%L" r))')
    body.append("")
    for pin in derived.pins:
        body.append(_pin_call(pin, has_ep=derived.ep_pad is not None))
    if spec.ep_present:
        body.append("    bAddEpPin(0.0 0.0)")
    body.append("")
    body.append(f"    asmWidth  = {_num(spec.asm_line_width)}")
    body.append(f"    silkWidth = {_num(spec.silk_line_width)}")
    body.append(f"    asmHalf   = {_num(derived.asm_half)}")
    body.append(f"    pbHalf    = {_num(derived.pb_half)}")
    body.append(f"    silkHalf  = {_num(derived.silk_half)}")
    body.append(f"    silkSpan  = {_num(derived.silk_span)}")
    body.append("    asmPos  = asmHalf")
    body.append("    asmNeg  = 0.0 - asmHalf")
    body.append("    pbPos   = pbHalf")
    body.append("    pbNeg   = 0.0 - pbHalf")
    body.append("    silkPos = silkHalf")
    body.append("    silkNeg = 0.0 - silkHalf")
    body.append("    spanPos = silkSpan")
    body.append("    spanNeg = 0.0 - silkSpan")
    body.append("")
    body.append(
        """    asmP = errset(axlDBCreateRectangle(
      list(asmNeg:asmNeg asmPos:asmPos) nil
      "PACKAGE GEOMETRY/ASSEMBLY_TOP"))
    bLog(sprintf(nil "ASSEMBLY rect = %L" asmP))
    unless(asmP && car(asmP)
      asmL = errset(axlDBCreateLine(
        list(asmNeg:asmNeg asmPos:asmNeg asmPos:asmPos
             asmNeg:asmPos asmNeg:asmNeg)
        asmWidth "PACKAGE GEOMETRY/ASSEMBLY_TOP"))
      bLog(sprintf(nil "ASSEMBLY lines = %L" asmL))
    )"""
    )
    body.append("")
    body.append(
        """    pbObj = errset(axlDBCreateRectangle(
      list(pbNeg:pbNeg pbPos:pbPos) t
      "PACKAGE GEOMETRY/PLACE_BOUND_TOP"))
    bLog(sprintf(nil "PLACE_BOUND rect = %L" pbObj))
    pbShape = if(pbObj then car(pbObj) else nil)
    pbShape = if(pbShape then car(pbShape) else nil)
    bLog(sprintf(nil "PLACE_BOUND dbid = %L" pbShape))"""
    )
    body.append("    when(pbShape")
    body.append("      r = errset(axlDBAddProp(")
    body.append(
        f'        list(pbShape) list("PACKAGE_HEIGHT_MAX" '
        f'"{spec.height_property_value}")))'
    )
    body.append('      bLog(sprintf(nil "PLACE_BOUND height prop = %L" r))')
    body.append("      unless(r && car(r)")
    body.append(
        '        bLog(sprintf(nil "PROP object types = %L"\n'
        "          errset(axlDBCreatePropDictEntry(nil))))"
    )
    body.append(
        '        bLog(sprintf(nil "PROP dict entry = %L"\n'
        '          errset(axlDBCreatePropDictEntry(\n'
        '            "PACKAGE_HEIGHT_MAX" "real" t nil "mm" nil))))'
    )
    body.append(
        '        bLog(sprintf(nil "PROP retry = %L"\n'
        "          errset(axlDBAddProp(\n"
        '            list(pbShape) list("PACKAGE_HEIGHT_MAX" '
        f'"{spec.height_property_value}")))))'
    )
    body.append("      )")
    body.append("    )")
    body.append("")
    body.append(
        """    silkTop = errset(axlDBCreateLine(
      list(spanNeg:silkPos spanPos:silkPos)
      silkWidth "PACKAGE GEOMETRY/SILKSCREEN_TOP"))
    silkBot = errset(axlDBCreateLine(
      list(spanNeg:silkNeg spanPos:silkNeg)
      silkWidth "PACKAGE GEOMETRY/SILKSCREEN_TOP"))
    bLog(sprintf(nil "SILK top=%L bottom=%L" silkTop silkBot))"""
    )
    body.append("")
    if derived.pin1_marker is not None:
        west, east, top, bottom = derived.pin1_marker
        body.append(f"    triWest   = {_signed(west)}")
        body.append(f"    triEast   = {_signed(east)}")
        body.append(f"    triTop    = {_num(top)}")
        body.append(f"    triBottom = {_num(bottom)}")
        body.append(
            """    silkMark = errset(axlDBCreateLine(
      list(triWest:triTop triEast:triTop triWest:triBottom triWest:triTop)
      silkWidth "PACKAGE GEOMETRY/SILKSCREEN_TOP"))
    bLog(sprintf(nil "SILK pin1 marker=%L" silkMark))"""
        )
        body.append("")
    body.append(
        "    to = make_axlTextOrientation(\n"
        f'      ?textBlock "{spec.refdes_text_block}" ?rotation 0.0 '
        '?mirrored nil ?justify "center")'
    )
    body.append(f"    refdesY = {_num(derived.refdes_silk_y)}")
    body.append(
        "    refA = errset(axlDBCreateText(\n"
        f'      "{spec.refdes_prefix}" 0.0:0.0 to "REF DES/ASSEMBLY_TOP" nil))'
    )
    body.append(
        "    refS = errset(axlDBCreateText(\n"
        f'      "{spec.refdes_prefix}" 0.0:refdesY to "REF DES/SILKSCREEN_TOP" nil))'
    )
    body.append('    bLog(sprintf(nil "REFDES asm=%L silk=%L" refA refS))')
    body.append("")
    body.append("    bDumpDesign()")
    body.append("")
    body.append(
        "    r = errset(axlSaveDesign(\n"
        '      ?design strcat(bWork "/" bName ".dra")\n'
        "      ?noMru t ?noConfirm t))"
    )
    body.append('    bLog(sprintf(nil "SAVE dra = %L" r))')
    body.append("")
    body.append(
        "    r = errset(axlCompileSymbol(\n"
        '      ?symbol strcat(bWork "/" bName)\n'
        '      ?type "package" ?silent t ?silentOnOverwrite t))'
    )
    body.append('    bLog(sprintf(nil "COMPILE psm = %L" r))')
    body.append("")
    body.append('    bLog("==== BUILD END ====")')
    body.append("    t")
    body.append("  )")
    body.append(")")

    header = _preamble(spec, work_dir, "build.log")
    procs = "\n\n".join(lines)
    return (
        f"{header}\n\n"
        f'{_log_procedure("bLog", "bLogF", "LOG_OPEN_FAILED")}\n\n'
        f"{procs}\n\n"
        f"procedure(bMain()\n"
        f"  prog((\n"
        f"      pd r units accuracy\n"
        f"      asmHalf pbHalf silkHalf silkSpan asmWidth silkWidth\n"
        f"      asmPos asmNeg pbPos pbNeg silkPos silkNeg spanPos spanNeg\n"
        f"      landX landY epX epY\n"
        f"      triWest triEast triTop triBottom\n"
        f"      refdesY to asmP asmL pbObj pbShape\n"
        f"      silkTop silkBot silkMark refA refS\n"
        f"    )\n"
        + "\n".join(body)
        + "\n\n"
        f'printf("AFC_{spec.name}_CORE_LOADED\\n")\n'
    )


# ── verify.il / props.il ─────────────────────────────────────────


def emit_verify_skill(spec: PackageSpec, work_dir: Path) -> str:
    """渲染 ``verify.il``：重新打开成品，回读引脚与对象几何。

    顺序刻意「先安全后危险」—— 属性读取放最后，这样 SKILL 硬崩也不会
    丢掉已写进 verify.log 的证据（源程序 verify.il 的注释原话）。
    """
    header = _preamble(spec, work_dir, "verify.log")
    return f"""{header}

{_log_procedure("bV", "bVLogF", "VERIFY_LOG_OPEN_FAILED")}

procedure(bVerify()
  prog((pd d pins sel objs)
    bV("==== VERIFY START ====")
    bV(sprintf(nil "version=%L" axlVersion('fullVersion)))
    bV(sprintf(nil "designType=%L" errset(axlDesignType(t))))
    pd = errset(axlGetParam("paramDesign"))
    when(pd && car(pd)
      bV(sprintf(nil "units=%L accuracy=%L extents=%L"
        errset(car(pd)->units)
        errset(car(pd)->accuracy)
        errset(car(pd)->bBox)))
    )
    d = errset(axlDBGetDesign())
    when(d && car(d)
      pins = errset(car(d)->pins)
      pins = if(pins then car(pins) else nil)
      bV(sprintf(nil "pin_count=%L" if(pins then length(pins) else 0)))
      when(pins
        foreach(p pins
          bV(sprintf(nil "PIN number=%L padstack=%L location=%L bbox=%L rot=%L"
            errset(p->number) errset(p->padstack) errset(p->location)
            errset(p->bBox) errset(p->rotation)))
        )
      )
    )
    axlSetFindFilter(
      ?enabled list("noall" "alltypes")
      ?onButtons list("noall" "alltypes"))
    errset(axlAddSelectAll())
    sel = errset(axlGetSelSet())
    objs = if(sel then car(sel) else nil)
    bV(sprintf(nil "object_count=%L" if(objs then length(objs) else 0)))
    when(objs
      foreach(o objs
        bV(sprintf(nil "OBJ type=%L layer=%L bbox=%L"
          errset(o->objType) errset(o->layer) errset(o->bBox)))
      )
    )
    when(objs
      foreach(o objs
        bV(sprintf(nil "PROPOBJ layer=%L fill=%L prop=%L"
          errset(o->layer) errset(o->fill) errset(o->prop)))
      )
    )
    bV("==== VERIFY END ====")
    t
  )
)

printf("AFC_{spec.name}_VERIFY_LOADED\\n")
"""


def emit_props_skill(spec: PackageSpec, work_dir: Path) -> str:
    """渲染 ``props.il``：确认 PACKAGE_HEIGHT_MAX 熬过存盘-重开这一遭。

    这是``PACKAGE_HEIGHT_MAX`` 唯一可靠的验证方式 —— 该属性在 v1 里赋值失败
    且没有任何兜底日志，最终版才靠字典注册成功（``props.log`` 里的
    ``((PACKAGE_HEIGHT_MAX "0.8 MM"))`` 是唯一黄金证据）。
    """
    header = _preamble(spec, work_dir, "props.log")
    return f"""{header}

{_log_procedure("bP", "bPLogF", "PROP_LOG_OPEN_FAILED")}

procedure(bProps()
  prog((sel objs)
    bP("==== PROPERTY CHECK START ====")
    axlSetFindFilter(
      ?enabled list("noall" "alltypes")
      ?onButtons list("noall" "alltypes"))
    errset(axlAddSelectAll())
    sel = errset(axlGetSelSet())
    objs = if(sel then car(sel) else nil)
    bP(sprintf(nil "object_count=%L" if(objs then length(objs) else 0)))
    when(objs
      foreach(o objs
        bP(sprintf(nil "OBJ layer=%L" errset(o->layer)))
        bP(sprintf(nil "  props=%L" errset(axlDBGetProperties(o))))
      )
    )
    bP("==== PROPERTY CHECK END ====")
    t
  )
)

printf("AFC_{spec.name}_PROPS_LOADED\\n")
"""


# ── 运行装置（ilinit 与 .scr）─────────────────────────────────────


def emit_allegro_ilinit(target_il: Path) -> str:
    """``allegro.ilinit``：Allegro 只自动加载**启动 cwd** 里的这一个文件。

    所以每次跑都必须把 cwd 设成 ``work_dir``，并让本文件指向本次要用的 .il。
    """
    return (
        "; auto-loaded by Allegro from the launch cwd\n"
        f'; swap this path to run verify.il / props.il instead\n'
        f'load("{_posix(target_il)}")\n'
    )


def emit_script(entry: str) -> str:
    """``build.scr`` 形式的剧本：调入口过程后强制退出。

    ``skill (axlOSExit 0)`` 保证无 GUI 残留、退出码可控 —— 没有它，
    无头模式会一直挂着。
    """
    return f"skill ({entry})\nskill (axlOSExit 0)\n"


def write_skill_package(
    spec: PackageSpec, derived: DerivedPackage, work_dir: Path
) -> dict[str, Path]:
    """一次写齐整套运行装置，返回 ``{逻辑名: 路径}``。

    写成一套是刻意的：``allegro.ilinit`` 与 ``*.scr`` 必须同步切换，
    分两次手工写就会对不上（源程序的注释把这条约定写在了 ilinit 里）。
    """
    work_dir = Path(work_dir)
    work_dir.mkdir(parents=True, exist_ok=True)
    stem = spec.name.lower()

    build_il = work_dir / f"build_{stem}.il"
    verify_il = work_dir / f"verify_{stem}.il"
    props_il = work_dir / f"props_{stem}.il"

    written: dict[str, Path] = {}
    for key, path, text in (
        ("build_il", build_il, emit_build_skill(spec, derived, work_dir)),
        ("verify_il", verify_il, emit_verify_skill(spec, work_dir)),
        ("props_il", props_il, emit_props_skill(spec, work_dir)),
        ("build_scr", work_dir / "build.scr", emit_script("bMain")),
        ("verify_scr", work_dir / "verify.scr", emit_script("bVerify")),
        ("props_scr", work_dir / "props.scr", emit_script("bProps")),
    ):
        path.write_text(text, encoding="utf-8")
        written[key] = path

    # ilinit 默认指向 build；verify / props 阶段由 runner 切换。
    ilinit = work_dir / "allegro.ilinit"
    ilinit.write_text(emit_allegro_ilinit(build_il), encoding="utf-8")
    written["ilinit"] = ilinit
    return written
